### ISSUE TITLE
Program crashes when trying to recognize an image

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract4java/tesseract4java#19]
[hs_err_pid6340.log.txt](https://github.com/tesseract4java/tesseract4java/files/429475/hs_err_pid6340.log.txt)

It was trying to recognize a copy of 
https://github.com/tesseract-ocr/tesseract/blob/master/testing/eurotext.tif

with english traineddata

**Comment by pvorb** [comment]
Thanks for the bug report. I'll have a look.

Did you use the batch recognition or recognition tab?

**Comment by pvorb** [comment]
Unfortunately I cannot reproduce the error. Does it also occur with other traineddata files or images?

**Comment by Shreeshrii** [comment]
This was just with the recognition tab. I tried with various images/traineddata. The program window just disappears without any dialogue. I later found the error logs in the directory where the jar file is.

I will test again later and report.

**Comment by Shreeshrii** [comment]
Seems to be some conflict with libtesseract. Now program does not start - just creates error log ..

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x68d7359d, pid=7672, tid=0x000007a0
#
# JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
# Java VM: Java HotSpot(TM) Client VM (25.101-b13 mixed mode, sharing windows-x86 )
# Problematic frame:
# C  [libtesseract-3.dll+0x17359d]
#
```

**Comment by pvorb** [comment]
> The program window just disappears without any dialogue.

Unfortunately it is not easy to prevent the JVM from crashing when there's such an `EXCEPTION_ACCESS_VIOLATION`. The only way would be to run Tesseract from another JVM process, which would make things more complex -- but probably that's the way to go.

Thanks for the new error log. This seems to be a similar but different issue than your problem yesterday. I can see from the log that the error occurred when running batch recognition. Probably you selected a traineddata file that causes Tesseract (or at least the bundled dll) to crash.

Yesterday the error occurred directly in the recognition tab, so it is a different problem, but both should be solved.

If you can't start the software any more, you can delete the Windows Registry key `HKEY_CURRENT_USER\Software\JavaSoft\Prefs\de\vorb\tesseract\gui\model\training_file`. Alternatively, you can change it to another traineddata file (try "eng").

**Comment by pvorb** [comment]
It would be great if you could send me the traineddata file, so I can reproduce and fix the error.

**Comment by Shreeshrii** [comment]
I deleted the Windows registry entry and now it is NOT crashing. You may close the issue.

**Comment by Shreeshrii** [comment]
Problem was coming with the eng.traineddata also but NOT anymore - so it was related to conflict because of pointing to an external directory for tesseract executable.

Qn. Is eng.traineddata included with program?

**Comment by pvorb** [comment]
No, it's not included with the program. The program has no bundled traineddata files.
