### ISSUE TITLE
project gui: Compilation failure

### ISSUE THREAD

**Issue by lowsury** [tesseract4java/tesseract4java#34]
[ERROR] tesseract4java-develop/gui/src/main/java/de/vorb/tesseract/
gui/controller/TesseractTrainer.java:[107,97] 找不到符号

**Comment by lowsury** [comment]
![image](https://cloud.githubusercontent.com/assets/7733424/18668125/3c7ccaf4-7f66-11e6-939d-c4ce9efb8100.png)
can not find the symbol de.vorb.tesseract.gui.view.dialogs.PreferencesDialog.KEY_EXEC_DIR

**Comment by pvorb** [comment]
This got fixed in 7d60cfbaab590f99bc173c5249cbd02d91df806e
