### ISSUE TITLE
windows 10 installation issue

### ISSUE THREAD

**Issue by wilfridcariou** [tesseract4java/tesseract4java#35]
When I run the executable jar file tesseract4java-0.1.0-windows-x86_64.jar on my computer, nothing  occur. Did I made a mistake?  (message: No jnelpt libray in java path)

My config: Windows 10 64 bits java 8.101

**Comment by pvorb** [comment]
Can you run `java -version` in a CMD and post the result here? You probably have a 32-bit Java installed on your 64-bit Windows, in which case you'd need to use the 32-bit version of tesseract4java.

**Comment by wilfridcariou** [comment]
You solve my problem! I am using 32 bits java...
I downloaded the tesseract4java-0.1.0-windows-x86.jar version with success.

**Comment by pvorb** [comment]
This is a common problem on Windows systems, which I should mention in the README.
