### ISSUE TITLE
begining with your programm

### ISSUE THREAD

**Issue by wilfridcariou** [tesseract4java/tesseract4java#36]
Hello
I am very interested in your work.
I downloaded Tesseract from the Github repository of the University of Mannheim https://github.com/UB-Mannheim/tesseract
I made a new porject Then I made links between Tesseract and your software (preferences). I gets no results for recognition ("please select a trainnig file). I'm really sorry to bother you but  I still insist, because your work represents a very big step forward for me. I search for explanations on your repository but without success.

Thank you for your help.

**Comment by pvorb** [comment]
There's some (incomplete) [documentation in the wiki](https://github.com/tesseract4java/tesseract4java/wiki/Usage).

**Comment by wilfridcariou** [comment]
Is the wiki relative to tesseract4java-0.1.0-windows-x86.jar? I  am not sure  to understand  the  Important settings section.

**Comment by pvorb** [comment]
Yes it is. But I agree the configuration process is not straight forward for Tesseract newcomers. Thus I [updated the instructions](https://github.com/tesseract4java/tesseract4java/wiki/Usage#installing-tesseract-language-files) and hope it will be clearer now. If it's still not straight-forward to get up and running, feel free to complain about it here or edit the wiki to improve it. ;)

**Comment by wilfridcariou** [comment]
Ok Thank you for you wiki updated. I will try to hang on because I believe that you GUI would able to democratize Tesseract OCR.

**Comment by pvorb** [comment]
:)
