### ISSUE TITLE
we can't find the ocrevalUAtion version "1.3.4-SNAPSHOT "

### ISSUE THREAD

**Issue by brucexx** [tesseract4java/tesseract4java#41]
hi I use the maven clean install   and find that the version of   ocrevalUAtion  in pom.xml  "1.3.4-SNAPSHOT" not exists , and ..
i search it in github https://github.com/tesseract4java/ocrevalUAtion/releases
the max version is 1.3.3  
so ... can you help me to get the version?? thx

**Comment by pvorb** [comment]
1.3.4-SNAPSHOT is the current development version. You need to clone the [tesseract4java/ocrevalUAtion](https://github.com/tesseract4java/ocrevalUAtion) and then install it using `mvn install`. Then you should be able to build tesseract4java.

**Comment by brucexx** [comment]
i did that... but the version 1.3.3 cannot be built because some classes are in 1.3.4
for example:
BatchExecutor   line 218 ,221 
and the error following:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project gui: Compilation failure: Compilation failure:
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/controller/TesseractController.java:[55,29] 找不到符号
[ERROR] 符号:   类 Parameters
[ERROR] 位置: 程序包 eu.digitisation.input
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/controller/TesseractController.java:[56,29] 找不到符号
[ERROR] 符号:   类 WarningException
[ERROR] 位置: 程序包 eu.digitisation.input
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/OCRTask.java:[14,29] 找不到符号
[ERROR] 符号:   类 Parameters
[ERROR] 位置: 程序包 eu.digitisation.input
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/BatchExecutor.java:[12,29] 找不到符号
[ERROR] 符号:   类 Parameters
[ERROR] 位置: 程序包 eu.digitisation.input
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/BatchExecutor.java:[13,29] 找不到符号
[ERROR] 符号:   类 WarningException
[ERROR] 位置: 程序包 eu.digitisation.input
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/controller/TesseractController.java:[594,19] 找不到符号
[ERROR] 符号:   类 Parameters
[ERROR] 位置: 类 de.vorb.tesseract.gui.controller.TesseractController
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/controller/TesseractController.java:[594,41] 找不到符号
[ERROR] 符号:   类 Parameters
[ERROR] 位置: 类 de.vorb.tesseract.gui.controller.TesseractController
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/controller/TesseractController.java:[604,18] 找不到符号
[ERROR] 符号:   类 WarningException
[ERROR] 位置: 类 de.vorb.tesseract.gui.controller.TesseractController
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/OCRTask.java:[183,31] 找不到符号
[ERROR] 符号:   类 Parameters
[ERROR] 位置: 类 de.vorb.tesseract.gui.work.OCRTask
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/OCRTask.java:[183,53] 找不到符号
[ERROR] 符号:   类 Parameters
[ERROR] 位置: 类 de.vorb.tesseract.gui.work.OCRTask
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/OCRTask.java:[202,38] 找不到符号
[ERROR] 符号:   方法 getStats()
[ERROR] 位置: 类型为eu.digitisation.output.Report的变量 rep
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/BatchExecutor.java:[218,55] 不兼容的类型: java.nio.file.DirectoryStream<java.nio.file.Path>无法转换为java.io.File
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/BatchExecutor.java:[221,31] 找不到符号
[ERROR] 符号:   类 Parameters
[ERROR] 位置: 类 de.vorb.tesseract.gui.work.BatchExecutor.CompletionCallback
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/BatchExecutor.java:[221,55] 找不到符号
[ERROR] 符号:   类 Parameters
[ERROR] 位置: 类 de.vorb.tesseract.gui.work.BatchExecutor.CompletionCallback
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/BatchExecutor.java:[238,41] 找不到符号
[ERROR] 符号:   方法 getStats()
[ERROR] 位置: 类型为eu.digitisation.output.Report的变量 report
[ERROR] /Users/baidu/ocr_test/tesseract4java/gui/src/main/java/de/vorb/tesseract/gui/work/BatchExecutor.java:[240,44] 找不到符号
[ERROR] 符号:   类 WarningException
[ERROR] 位置: 类 de.vorb.tesseract.gui.work.BatchExecutor.CompletionCallback
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by brucexx** [comment]
and ??? nobody help?

**Comment by pvorb** [comment]
Didn't I already say you need 1.3.4-SNAPSHOT instead of 1.3.3? Why are you trying to build 1.3.3 again?

**Comment by pvorb** [comment]
~~~
git clone https://github.com/tesseract4java/ocrevalUAtion.git
cd ocrevalUAtion
git checkout 75f652d36c72d9ee827707e73a0c412f430f74c6
mvn install
~~~

**Comment by cornerman54** [comment]
I mean it doesn’t open de tiff file hourglass

 

 

 

Jannes Hoekman

 

Van: Paul Vorbach <notifications@github.com> 
Verzonden: zaterdag 10 maart 2018 21:47
Aan: tesseract4java/tesseract4java <tesseract4java@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [tesseract4java/tesseract4java] we can't find the ocrevalUAtion version "1.3.4-SNAPSHOT " (#41)

 

git clone https://github.com/tesseract4java/ocrevalUAtion.git
cd ocrevalUAtion
git checkout 75f652d36c72d9ee827707e73a0c412f430f74c6
mvn install
