### ISSUE TITLE
[issue] No preview displayed

### ISSUE THREAD

**Issue by FedericaSpini** [tesseract4java/tesseract4java#42]
The program executes without errors. 

![schermata del 2017-03-24 11-49-28](https://cloud.githubusercontent.com/assets/20460665/24291134/f8b20038-1087-11e7-923c-9482b0d4b1f5.png)

However, if I click on preview nothing happens.
Any ideas about what the problem could be?

I'm using Java8 on Linux Mint.

Thanks

**Comment by pvorb** [comment]
Do you have an image where a preview can be displayed or is this a general problem?

**Comment by FedericaSpini** [comment]
This is a general problem.

Il 28 mar 2017 8:56 AM, "Paul Vorbach" <notifications@github.com> ha
scritto:

**Comment by pvorb** [comment]
Ok. Maybe this is related to #38 but I really don't know yet.

**Comment by FedericaSpini** [comment]
Ok, thank you!
However I'm looking at the code trying to solve the problem.

Do you have any hints to give about where  the problem could be? 
Which is the class that manage the view of the preprocessed image?

**Comment by pvorb** [comment]
There's the `PreprocessingWorker`, which calls the `Preprocessor` to calculate the `preprocessedImg` and that is then displayed in the `PreprocessingPane`.

Thanks for having a look.

**Comment by mohamnag** [comment]
having the exact same problem on osx 10.12 using java 8 and tesseract 3.05. I never get an image in the preview panel.

**Comment by FedericaSpini** [comment]
Hello! 
I think I've found the problem: when the system reads my image and converts it to a `BufferedImage`, its type is not supported by the preprocessing process.
So at the moment, I'm converting the type of the image to `TYPE_INT_RGB` and it seems to work fine.

I modified the method `doInBackground` in the `PreprocessingWorker` class as follows:

    @Override
    protected ImageModel doInBackground() throws Exception {
        Files.createDirectories(destinationDir);

        final Path destFile = destinationDir.resolve(FileNames.replaceExtension(
                sourceFile, "png").getFileName());

        final BufferedImage readImg = ImageIO.read(sourceFile.toFile());

        //**************************

        final BufferedImage sourceImg = new BufferedImage(readImg.getWidth(), readImg.getHeight(),1 );
        Graphics2D g2d= sourceImg.createGraphics();
        g2d.drawImage(readImg, 0, 0, null);
        g2d.dispose();

        //**************************

        final BufferedImage preprocessedImg = preprocessor.process(sourceImg);
        ImageIO.write(preprocessedImg, "PNG", destFile.toFile());

        return new ImageModel(sourceFile, sourceImg, destFile, preprocessedImg);
    }

**Comment by pvorb** [comment]
Thanks @FedericaSpini, that solution looks good. I've extracted PR #44. Would you mind to test it with that version again?

**Comment by FedericaSpini** [comment]
I'm having some problems compiling it: 
![errscreen](https://cloud.githubusercontent.com/assets/20460665/26347897/45e72174-3fab-11e7-9a2b-1b5554734dbe.PNG)

Some of the images which I had problem with are these: [samples.zip](https://github.com/tesseract4java/tesseract4java/files/1021675/samples.zip)
