### ISSUE TITLE
Information about training

### ISSUE THREAD

**Issue by FedericaSpini** [tesseract4java/tesseract4java#43]
Hello!

I'd like to try the training feature of tesseract using the tesseract4java GUI.
I saw that there is an option to do it under Tools, but I can't find any information on how to use it (I found only a link to the tesseract wiki, but since I'm a beginner with tesseract it's a bit too much).

Shall someone give me some tips on how to use it?

**Comment by pvorb** [comment]
There's also the [usage](https://github.com/tesseract4java/tesseract4java/wiki/Usage) wiki page of this project, but I admit that you need to have a fairly good understanding of Tesseract first.

**Comment by FedericaSpini** [comment]
Yeah, I'm reading the docs... However at the moment I'm stuck with a problem (and I don't understand if  I'm doing it wrong, if it's a problem with tesseract or with tesseract4java).

I've correctly created the .box files in the "preprocessed" folder of the project.
But I can't complete the mfTraining phase:

Initially the process didn't find the imageName.font_properties file, but I should have fixed that  adding it manually.
Now the problem printed in the trained.log file is:

Error: Unable to open /path/tesseract-project/preprocessed/fan1.tr!
"Fatal error encountered!" == NULL:Error:Assert failed:in file globaloc.cpp, line 75

Do I have to generate the .tr file with tesseract without using tesseract4java?

**Comment by pvorb** [comment]
Yes, you need to create *.tr files yourself. Tools &rarr; Tesseract Trainer (Ctrl + Shift + T) can help you with that.
