### ISSUE TITLE
Error opening data file

### ISSUE THREAD

**Issue by xiomatic** [tesseract4java/tesseract4java#58]
Language cannot be loaded due to its path being defined as /home/travis/...

` java -jar tesseract4java-0.3.0-SNAPSHOT-standalone.jar 
Error opening data file /home/travis/build/javacpp-presets/tesseract/cppbuild/linux-x86_64/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
`

**Comment by pvorb** [comment]
You should probably set the TESSDATA_PREFIX variable.
