### ISSUE TITLE
Java Exception occurred

### ISSUE THREAD

**Issue by Chiff749** [tesseract4java/tesseract4java#60]
I wish to recognise a minority language from Central Africa. I'm  a Linux novice. My system is a fork from Linux Mint 20.1 which has openjdk1.11 and jre1.11. Installation of the 0.2.1 release with Maven, following the instructions at https://github.com/tesseract4java/tesseract4java seemed to go smoothly. However, running the .jar file per the instructions results, after a few seconds, in the report "A Java Exception has occurred." Web searches have shed no light on cause or cure.

How would I fix this? What further information is needed? Where would I find that? (Remember, I'm a novice.)

**Comment by pvorb** [comment]
I suggest that you run again with `java -jar tesseract4java.jar` in a terminal. This should give you details about what's wrong.

I think I've never tested the application with Java 11, so there might be issues. Maybe you have to try again with Java 8.

**Comment by pvorb** [comment]
And if you don't want to waste time, try [VietOCR](http://vietocr.sourceforge.net/) first. It's a GUI for Tesseract that is actually supported by the author. I only react to comments once in a while, but I don't work on the project any more.

**Comment by Chiff749** [comment]
Thanks Paul. I will try both suggestions.


DP


------ Original Message ------
From: "Paul Vorbach" ***@***.***>
To: "tesseract4java/tesseract4java" ***@***.***>
Cc: "Chiff749" ***@***.***>; "Author" 
***@***.***>
Sent: Thursday, 18 Mar, 21 At 21:13
Subject: Re: [tesseract4java/tesseract4java] Java Exception occurred 
(#60)


And if you don't want to waste time, try VietOCR 
<http://vietocr.sourceforge.net/>  first. It's a GUI for Tesseract that 
is actually supported by the author. I only react to comments once in a 
while, but I don't work on the project any more.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/tesseract4java/tesseract4java/issues/60#issuecomment-802303649> 
, or unsubscribe

**Comment by Chiff749** [comment]
Hi,


It gave this:

$ java -jar tesseract4java.jar
Error: Unable to access jarfile tesseract4java.jar



leaving me none the wiser :-(

DP


------ Original Message ------
From: "Paul Vorbach" ***@***.***>
To: "tesseract4java/tesseract4java" ***@***.***>
Cc: "Chiff749" ***@***.***>; "Author" 
***@***.***>
Sent: Thursday, 18 Mar, 21 At 21:09
Subject: Re: [tesseract4java/tesseract4java] Java Exception occurred 
(#60)


I suggest that you run again with java -jar tesseract4java.jar in a 
terminal. This should give you details about what's wrong.
I think I've never tested the application with Java 11, so there might 
be issues. Maybe you have to try again with Java 8.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/tesseract4java/tesseract4java/issues/60#issuecomment-802301137> 
, or unsubscribe

**Comment by pvorb** [comment]
Oh, this wasn't clear. You need to replace tesseract4java.jar with the exact path and filename of the downloaded jar file. For example

    java -jar ~/Downloads/tesseract4java-0.2.1-linux-x86_64.jar

This really depends on the version you downloaded and where you stored the downloaded file.

**Comment by Chiff749** [comment]
Thanks; I figured that could be the problem just after "lights out" last 
night.

------ Original Message ------
From: "Paul Vorbach" ***@***.***>
To: "tesseract4java/tesseract4java" ***@***.***>
Cc: "Chiff749" ***@***.***>; "Author" 
***@***.***>
Sent: Thursday, 18 Mar, 21 At 22:12
Subject: Re: [tesseract4java/tesseract4java] Java Exception occurred 
(#60)


Oh, this wasn't clear. You need to replace tesseract4java.jar with the 
exact path and filename of the downloaded jar file. For example java 
-jar ~/Downloads/tesseract4java-0.2.1-linux-x86_64.jar
This really depends on the version you downloaded and where you stored 
the downloaded file.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/tesseract4java/tesseract4java/issues/60#issuecomment-802341059> 
, or unsubscribe
