### ISSUE TITLE
Does this still work ?

### ISSUE THREAD

**Issue by AdnanCukur** [tesseract4java/tesseract4java#64]
Does this still work ? i literally cant get it to do anything, preview button doesnt do anything, tesseract trainer only results in a null error with nothing written in the trainer log,
![image](https://user-images.githubusercontent.com/15705027/127670490-eacbe2ad-5afe-4530-9781-c61a0c9a019d.png)

**Comment by pvorb** [comment]
Image file format support is limited and error messages might not be very helpful.

But as I'm no longer working on this tool, I suggest to look for alternatives like VietOCR, which is still kept up-to-date.
