### ISSUE TITLE
Build fail (ocrevalUAtion)

### ISSUE THREAD

**Issue by jhnwnstd** [tesseract4java/tesseract4java#66]
I'm building on Windows 10.0.19044 Build 19044, java 18.0.1.1 2022-04-22, Apache Maven 3.8.6. I've got no experience with any of this. ocrevalUAtion is where it fails. I can provide more information if needed.

Running: 

mvn clean package -Pstandalone

Get this error message:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] tesseract4java                                                     [pom]
[INFO] ocrevalUAtion                                                      [jar]
[INFO] tools                                                              [jar]
[INFO] gui                                                                [jar]
[INFO]
[INFO] ------------------< de.vorb.tesseract:tesseract4java >------------------
[INFO] Building tesseract4java 0.3.0-SNAPSHOT                             [1/4]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tesseract4java ---
[INFO]
[INFO] ------------------< de.vorb.tesseract:ocrevalUAtion >-------------------
[INFO] Building ocrevalUAtion 0.3.0-SNAPSHOT                              [2/4]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for tesseract4java 0.3.0-SNAPSHOT:
[INFO]
[INFO] tesseract4java ..................................... SUCCESS [  0.130 s]
[INFO] ocrevalUAtion ...................................... FAILURE [  0.229 s]
[INFO] tools .............................................. SKIPPED
[INFO] gui ................................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.478 s
[INFO] Finished at: 2022-06-23T23:44:14-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ocrevalUAtion: Could not resolve dependencies for project de.vorb.tesseract:ocrevalUAtion:jar:0.3.0-SNAPSHOT: Failed to collect dependencies at javax.media.jai:com.springsource.javax.media.jai.core:jar:1.1.3: Failed to read artifact descriptor for javax.media.jai:com.springsource.javax.media.jai.core:jar:1.1.3: Could not transfer artifact javax.media.jai:com.springsource.javax.media.jai.core:pom:1.1.3 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [com.springsource.repository.bundles.external (http://repository.springsource.com/maven/bundles/external, default, releases+snapshots)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ocrevalUAtion

**Comment by pvorb** [comment]
I recommend using a different tool like VietOCR. This software is no longer working.
